apiVersion: apps/v1
kind: Deployment

metadata:
  name: sirius-runtime

spec:
  replicas: 3

  selector:
    matchLabels:
      app: sirius-runtime

  template:
    metadata:
      labels:
        app: sirius-runtime

    spec:

      containers:

      - name: sirius-runtime

        image: sirius-runtime:latest

        ports:
        - containerPort: 8000

        resources:
          limits:
            memory: "2Gi"
            cpu: "2"

          requests:
            memory: "512Mi"
            cpu: "500m"
